-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE hermes_tags (
  ht_id BIGSERIAL NOT NULL,
  ht_wiki TEXT NOT NULL,
  ht_language TEXT NOT NULL,
  ht_page_id INT NOT NULL,
  ht_page_title TEXT NOT NULL,
  ht_section TEXT DEFAULT NULL,
  ht_tag TEXT NOT NULL,
  ht_order INT DEFAULT 0 NOT NULL,
  PRIMARY KEY(ht_id)
);

CREATE INDEX ht_tag_lang ON hermes_tags (ht_tag, ht_language);

CREATE INDEX ht_wiki_page ON hermes_tags (ht_wiki, ht_page_id);

CREATE UNIQUE INDEX ht_wiki_page_tag ON hermes_tags (ht_wiki, ht_page_id, ht_tag);


CREATE TABLE hermes_languages (
  hl_language TEXT NOT NULL,
  hl_wiki TEXT NOT NULL,
  hl_base SMALLINT DEFAULT 1 NOT NULL,
  PRIMARY KEY(hl_language)
);

CREATE INDEX hl_wiki ON hermes_languages (hl_wiki);
