-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/hermes_tags (
  ht_wiki BLOB NOT NULL,
  ht_page_id INTEGER NOT NULL,
  ht_tag BLOB NOT NULL,
  ht_namespace_id INTEGER DEFAULT 0 NOT NULL,
  ht_namespace_text BLOB DEFAULT '' NOT NULL,
  ht_translation_project BLOB DEFAULT NULL,
  ht_base_title BLOB NOT NULL,
  ht_section BLOB DEFAULT NULL,
  ht_order INTEGER DEFAULT 0 NOT NULL,
  PRIMARY KEY(ht_wiki, ht_page_id, ht_tag)
);

CREATE INDEX ht_wiki_page ON /*_*/hermes_tags (ht_wiki, ht_page_id);


CREATE TABLE /*_*/hermes_languages (
  hl_language BLOB NOT NULL,
  hl_wiki BLOB NOT NULL,
  hl_base SMALLINT DEFAULT 1 NOT NULL,
  PRIMARY KEY(hl_language)
);

CREATE INDEX hl_wiki ON /*_*/hermes_languages (hl_wiki);


CREATE TABLE /*_*/hermes_wikis (
  hw_wiki BLOB NOT NULL,
  hw_url BLOB NOT NULL,
  PRIMARY KEY(hw_wiki)
);
