-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/hermes_tags (
  ht_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ht_wiki BLOB NOT NULL, ht_language BLOB NOT NULL,
  ht_page_id INTEGER NOT NULL, ht_page_title BLOB NOT NULL,
  ht_section BLOB DEFAULT NULL, ht_tag BLOB NOT NULL,
  ht_order INTEGER DEFAULT 0 NOT NULL
);

CREATE INDEX ht_tag_lang ON /*_*/hermes_tags (ht_tag, ht_language);

CREATE INDEX ht_wiki_page ON /*_*/hermes_tags (ht_wiki, ht_page_id);

CREATE UNIQUE INDEX ht_wiki_page_tag ON /*_*/hermes_tags (ht_wiki, ht_page_id, ht_tag);


CREATE TABLE /*_*/hermes_languages (
  hl_language BLOB NOT NULL,
  hl_wiki BLOB NOT NULL,
  hl_base SMALLINT DEFAULT 1 NOT NULL,
  PRIMARY KEY(hl_language)
);

CREATE INDEX hl_wiki ON /*_*/hermes_languages (hl_wiki);
