-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/hermes_tags (
  ht_wiki VARBINARY(64) NOT NULL,
  ht_page_id INT NOT NULL,
  ht_tag VARBINARY(255) NOT NULL,
  ht_namespace_id INT DEFAULT 0 NOT NULL,
  ht_namespace_text VARBINARY(255) DEFAULT '' NOT NULL,
  ht_translation_project VARBINARY(35) DEFAULT NULL,
  ht_base_title VARBINARY(255) NOT NULL,
  ht_section VARBINARY(255) DEFAULT NULL,
  ht_order INT DEFAULT 0 NOT NULL,
  INDEX ht_wiki_page (ht_wiki, ht_page_id),
  PRIMARY KEY(ht_wiki, ht_page_id, ht_tag)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/hermes_languages (
  hl_language VARBINARY(35) NOT NULL,
  hl_wiki VARBINARY(64) NOT NULL,
  hl_base TINYINT(1) DEFAULT 1 NOT NULL,
  INDEX hl_wiki (hl_wiki),
  PRIMARY KEY(hl_language)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/hermes_wikis (
  hw_wiki VARBINARY(64) NOT NULL,
  hw_url VARBINARY(255) NOT NULL,
  PRIMARY KEY(hw_wiki)
) /*$wgDBTableOptions*/;
